server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        encrypt:
            enabled: false
        git:
          uri: https://github.com/devAlbuquerque/C0DES/tree/master/java/spring/microsservicos/microsservico-com-spring-cloud/repo/
          search-paths: fornecedor
          
          
          
          
